### ISSUE TITLE
Do not escape slashes in strings

### ISSUE THREAD

**Issue by saerdnaer** [opawg/podcast-hosts#14]
Hi @jamescridland,

could you change the export script which generates the `hosts.json` to not escape slashes in URL? PHPs `json_encode()` has an option for that.

e.g. `"hosturl": "http://www.abc.net.au",` instead of `"hosturl": "http:\/\/www.abc.net.au",`

**Comment by jamescridland** [comment]
The spec for the user-agents repo says:

> Backslashes ("\") should be escaped, so instead of ^Echo\/1\., the string should read ^Echo\\/1\\..

I confess not to know why, but that's the standard that I've used for this code as well. PHP deals happily with removing the escaped slashes.

Do let me know if it's an issue for you.
