### ISSUE TITLE
Add Podcasting 2.0 Supported Tags

### ISSUE THREAD

**Issue by GeorgeL9** [opawg/podcast-hosts#37]
I'd like to contribute back data from PodcastDb about the presence of Podcasting 2.0 supported tags per host. Is this something that this project wants?

How would we want to represent this data? I think just a "has_podcasting_20_tags" would be limiting. Maybe an array representation like ['funding','transcript'] which would be the <podcast:funding> but just the "funding", etc portion? I have data on each tag for each host.

**Comment by jamescridland** [comment]
Hi George!

This exists over here:
https://github.com/Podcastindex-org/web-ui/blob/master/server/data/apps.json

It's used by https://podnews.net/article/new-podcast-apps and https://podcastindex.org/apps as two examples.

Is that what you meant?

**Comment by GeorgeL9** [comment]
Ah that repo makes sense. It is missing quite a few hosting companies compared to this list. We can close this issue, and I will look at updating the data over there.
